### ISSUE TITLE
Sometimes releases are assigned to the wrong project

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/plugin-sentry#207]
**Describe the bug**  
Sometimes releases are not recorded at the correct project, i.e. javascript 6.1.3 is listed with project snmp.

**To Reproduce**  
I do not know how to reproduce

**Expected behavior**  
correct assignment

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/28575778/221038708-25a600b0-1655-4dc2-b855-74f0881146c0.png)

**Versions:**  
n/a

**Additional context**  
When using test-and-release.yml in conjunction with deploy step the sentry integration takes the project information from the values entred at test-and-relese.yml:
```
    steps:
      - uses: ioBroker/testing-action-deploy@v1
        with:
          node-version: '16.x'
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
        # When using Sentry for error reporting, Sentry can be informed about new releases
        # To enable create a API-Token in Sentry (User settings, API keys)
        # Enter this token as a GitHub secret (with name SENTRY_AUTH_TOKEN) in the repository options
        # Then uncomment and customize the following block:
          sentry: true
          sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-project: "iobroker-logparser"
          sentry-version-prefix: "iobroker.logparser"
          # If your sentry project is linked to a GitHub repository, you can enable the following option
          sentry-github-integration: true
```

If an incorrect project is listed ther, the release is registered with this incorrect project. (ie. snmp release 2.4.0 is registered with ns-client due to such an error). But I could not detect such a situation at discovergy or javascript.
